Repository andy-takker/organization_parser, pull requests merged in 2023-09, with the labels that each got.

#13 #12 Add rye to project
  .github/workflows/main.yml
  .github/workflows/release.yml
  .pre-commit-config.yaml
  .python-version
  README.md
  pyproject.toml
  requirements-dev.lock
  requirements-dev.txt
  requirements.lock
  requirements.txt
  src/main.py
  src/organization_parser/__init__.py
  src/organization_parser/__main__.py
  src/organization_parser/cli.py
  src/organization_parser/utils.py
Labels: enhancement

#14 #1 add function for all results from API
  .gitignore
  pyproject.toml
  src/organization_parser/__main__.py
  src/organization_parser/cli.py
  src/organization_parser/dto.py
  src/organization_parser/utils.py
Labels: enhancement

#16 Feature/issue 15
  .env.dev
  .github/workflows/main.yml
  .github/workflows/release.yml
  .gitignore
  .pre-commit-config.yaml
  .python-version
  Dockerfile
  README.md
  poetry.lock
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  src/__init__.py
  src/alembic.ini
  src/bot/__init__.py
  src/bot/config.py
  src/bot/db/__init__.py
  src/bot/db/base.py
  src/bot/db/factory.py
  src/bot/db/migrations/__init__.py
  src/bot/db/migrations/env.py
  src/bot/db/migrations/script.py.mako
  src/bot/db/migrations/versions/2023_09_07_18811e6c48be_init_db.py
  src/bot/db/mixins.py
  src/bot/db/models.py
  src/bot/db/provider.py
  src/bot/db/repositories/__init__.py
  src/bot/db/repositories/base.py
  src/bot/db/repositories/user.py
  src/bot/dialogs/__init__.py
  src/bot/dialogs/change_api_key.py
  src/bot/dialogs/commands.py
  src/bot/dialogs/main_menu.py
  src/bot/dialogs/registration.py
  src/bot/dialogs/request_parser.py
  src/bot/exceptions/__init__.py
  src/bot/factory.py
  src/bot/main.py
  src/bot/middlewares/__init__.py
  src/bot/middlewares/db.py
  src/bot/middlewares/settings.py
  src/bot/states.py
  src/bot/ui_commands.py
  src/bot/windows/__init__.py
  src/bot/windows/confirm.py
  src/bot/windows/input_form_field.py
  src/bot/windows/main_menu.py
  src/bot/windows/set_api_key.py
  src/core/__init__.py
  src/core/cli.py
  src/core/dto.py
  src/core/service/__init__.py
  src/core/service/async_client.py
  src/core/service/sync_client.py
  src/core/service/utils.py
  src/organization_parser/__init__.py
  src/organization_parser/__main__.py
Labels: enhancement

#17 Fix readme.md
  README.md
Labels: documentation

#18 Release 0.1.0
  .env.dev
  .github/workflows/main.yml
  .github/workflows/release.yml
  .gitignore
  .pre-commit-config.yaml
  Dockerfile
  README.md
  poetry.lock
  pyproject.toml
  src/__init__.py
  src/alembic.ini
  src/bot/__init__.py
  src/bot/config.py
  src/bot/db/__init__.py
  src/bot/db/base.py
  src/bot/db/factory.py
  src/bot/db/migrations/__init__.py
  src/bot/db/migrations/env.py
  src/bot/db/migrations/script.py.mako
  src/bot/db/migrations/versions/2023_09_07_18811e6c48be_init_db.py
  src/bot/db/mixins.py
  src/bot/db/models.py
  src/bot/db/provider.py
  src/bot/db/repositories/__init__.py
  src/bot/db/repositories/base.py
  src/bot/db/repositories/user.py
  src/bot/dialogs/__init__.py
  src/bot/dialogs/change_api_key.py
  src/bot/dialogs/commands.py
  src/bot/dialogs/main_menu.py
  src/bot/dialogs/registration.py
  src/bot/dialogs/request_parser.py
  src/bot/exceptions/__init__.py
  src/bot/factory.py
  src/bot/main.py
  src/bot/middlewares/__init__.py
  src/bot/middlewares/db.py
  src/bot/middlewares/settings.py
  src/bot/states.py
  src/bot/ui_commands.py
  src/bot/windows/__init__.py
  src/bot/windows/confirm.py
  src/bot/windows/input_form_field.py
  src/bot/windows/main_menu.py
  src/bot/windows/set_api_key.py
  src/core/__init__.py
  src/core/cli.py
  src/core/dto.py
  src/core/service/__init__.py
  src/core/service/async_client.py
  src/core/service/sync_client.py
  src/core/service/utils.py
Labels: release

#20 Release 0.1.1
  .github/workflows/release.yml
  poetry.lock
  pyproject.toml
Labels: release

#21 Fix release action
  .github/workflows/release.yml
Labels: release
